### ISSUE TITLE
use updated URL for wkhtmltopdf downloads

### ISSUE THREAD

**Issue by ashkulz** [agendrix/chef-agendrix-base#1]
Hello,

wkhtmltopdf has [moved the downloads provider](https://groups.google.com/d/msg/wkhtmltopdf-general/wZwTUol3mXI/GNVeyrKDdqIJ) from SourceForge to gna.org. As mentioned in the linked message, all earlier downloads have been removed from SourceForge and you are strongly advised to migrate to the new URLs. The following files in your repository will need to be updated:

* attributes/default.rb

It is recommended to either subscribe to the [mailing list](https://groups.google.com/forum/#!forum/wkhtmltopdf-general) or [Twitter feed](https://twitter.com/wkhtmltopdf) to receive updates on new releases and further changes.

Thanks,
wkhtmltopdf maintainer

**Comment by allaire** [comment]
@ashkulz Thanks for the heads up. Can I assume that you will follow the same naming standard for the version/unix distro? (see https://github.com/agendrix/chef-agendrix-base/commit/cb0bc7ca4e58b9cbdd9e956235d6b7a1b2f06159)

**Comment by ashkulz** [comment]
The naming convention for the file is not changed, but you will not get a correct URL with that commit -- it is `/wkhtmltopdf/0.12/0.12.2.1/<filename>` instead of just the version (otherwise there would too many directories to browse in future).
